version: 2.1

orbs:
  maven: circleci/maven@1.1

jobs:
  build:
    environment:
      CODACY_API_TOKEN: "$CODACY_API_TOKEN"
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run:
          name: "maven-build"
          command: |
            mvn -B clean package
      - run:
          name: "codacy"
          command: "bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r target/site/jacoco/jacoco.xml"
      - save_cache:
            paths:
              - ~/.m2
            key: v1-dependencies-{{ checksum "pom.xml" }}
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/site/jacoco/index.html

workflows:
  version: 2.1
  workflow:
    jobs:
      - build
